sudo:
  - false

language:
  - cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang

script:
  - which clang++
  - clang++ --version
  - clang++ -std=c++11 -stdlib=libc++ test.cpp -o prog && ./prog
